/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class dmpanel extends javax.swing.JPanel {

    /**
     * Creates new form dmpanel
     */
    public dmpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dmscroll = new javax.swing.JScrollPane();
        dmshow = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        dmscroll.setBackground(new java.awt.Color(255, 255, 255));
        dmscroll.setBorder(null);
        dmscroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        dmshow.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dmshowLayout = new javax.swing.GroupLayout(dmshow);
        dmshow.setLayout(dmshowLayout);
        dmshowLayout.setHorizontalGroup(
            dmshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1443, Short.MAX_VALUE)
        );
        dmshowLayout.setVerticalGroup(
            dmshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );

        dmscroll.setViewportView(dmshow);

        add(dmscroll);
        dmscroll.setBounds(1, 80, 1050, 570);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Direct Messages");
        add(jLabel2);
        jLabel2.setBounds(10, 20, 340, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane dmscroll;
    public javax.swing.JPanel dmshow;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
