
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class logindialog extends java.awt.Dialog {
int r,g,b;
  
    public logindialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    setSize(495,495);
 
   setBackground(Color.white);
Image icon=Toolkit.getDefaultToolkit().getImage("src\\folder\\icn.png");
setIconImage(icon);
lb2.setVisible(false);
        jt.requestFocus();


   
           
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jt = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt = new javax.swing.JButton();
        lb4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        closepn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(null);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 161, 242), 7));
        jPanel3.setAlignmentX(0.2F);
        jPanel3.setAlignmentY(0.2F);
        jPanel3.setPreferredSize(new java.awt.Dimension(495, 495));
        jPanel3.setLayout(null);

        jt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(0, 204, 255), java.awt.Color.white, new java.awt.Color(0, 204, 255)), "pin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(29, 161, 242))); // NOI18N
        jt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jt.setFocusCycleRoot(true);
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtMouseEntered(evt);
            }
        });
        jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtActionPerformed(evt);
            }
        });
        jPanel3.add(jt);
        jt.setBounds(30, 220, 280, 50);

        lb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(29, 161, 242));
        lb1.setText("Enter pin");
        jPanel3.add(lb1);
        lb1.setBounds(30, 180, 120, 20);

        lb2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(29, 161, 242));
        lb2.setText("get started...");
        jPanel3.add(lb2);
        lb2.setBounds(350, 420, 150, 40);

        bt.setBackground(new java.awt.Color(29, 161, 242));
        bt.setForeground(new java.awt.Color(255, 255, 255));
        bt.setText("SUBMIT");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        jPanel3.add(bt);
        bt.setBounds(30, 300, 130, 40);

        lb4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\twt1.png")); // NOI18N
        jPanel3.add(lb4);
        lb4.setBounds(20, 20, 280, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\pin.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(130, 160, 50, 50);

        closepn.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/close3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        closepn.add(jLabel2);
        jLabel2.setBounds(0, 0, 90, 90);

        jPanel3.add(closepn);
        closepn.setBounds(400, 20, 90, 90);

        add(jPanel3);
        jPanel3.setBounds(-3, -2, 530, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActionPerformed

    private void jtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseEntered
      lb2.setVisible(true);
    }//GEN-LAST:event_jtMouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
  closepn.setBackground(new Color(30,21,90));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
    closepn.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             logindialog dialog = new logindialog(new java.awt.Frame(), true);
           
        
                
  
 
               dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt;
    private javax.swing.JPanel closepn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField jt;
    public javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb4;
    // End of variables declaration//GEN-END:variables

}
