/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class profilepanel extends javax.swing.JPanel {

    /**
     * Creates new form profilepanel
     */
    public profilepanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        followerpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        followerpanel.setBackground(new java.awt.Color(204, 240, 255));
        followerpanel.setAutoscrolls(true);

        javax.swing.GroupLayout followerpanelLayout = new javax.swing.GroupLayout(followerpanel);
        followerpanel.setLayout(followerpanelLayout);
        followerpanelLayout.setHorizontalGroup(
            followerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        followerpanelLayout.setVerticalGroup(
            followerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(followerpanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 0, 500, 560);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        friendpanel.setBackground(new java.awt.Color(204, 240, 255));

        javax.swing.GroupLayout friendpanelLayout = new javax.swing.GroupLayout(friendpanel);
        friendpanel.setLayout(friendpanelLayout);
        friendpanelLayout.setHorizontalGroup(
            friendpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        friendpanelLayout.setVerticalGroup(
            friendpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(friendpanel);

        add(jScrollPane2);
        jScrollPane2.setBounds(520, 0, 500, 560);

        jPanel1.setBackground(new java.awt.Color(29, 161, 242));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 21, 90), 3, true));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Followers");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 230, 50);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Following");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(700, 0, 230, 50);

        add(jPanel1);
        jPanel1.setBounds(0, 560, 1056, 90);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel followerpanel;
    public javax.swing.JPanel friendpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
