/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class singlealert extends javax.swing.JPanel {

    /**
     * Creates new form singlealert
     */
    public singlealert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notif = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 240, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 161, 242), 3, true));
        setLayout(null);

        notif.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        notif.setForeground(new java.awt.Color(30, 21, 90));
        notif.setText("Loading....");
        add(notif);
        notif.setBounds(0, 0, 930, 120);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel notif;
    // End of variables declaration//GEN-END:variables
}
