
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class singlesearchtweet extends javax.swing.JPanel {

    /**
     * Creates new form singlesearchtweet
     */
    public singlesearchtweet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchphotolb = new javax.swing.JLabel();
        favoritecount = new javax.swing.JLabel();
        retweetlb = new javax.swing.JLabel();
        retweetcount = new javax.swing.JLabel();
        medialb = new javax.swing.JLabel();
        replycount = new javax.swing.JLabel();
        namelb = new javax.swing.JLabel();
        snlb = new javax.swing.JLabel();
        timelb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchtweet = new javax.swing.JTextArea();
        likelb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(null);

        searchphotolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(searchphotolb);
        searchphotolb.setBounds(10, 10, 90, 90);

        favoritecount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        favoritecount.setText("2");
        add(favoritecount);
        favoritecount.setBounds(360, 580, 40, 40);

        retweetlb.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\A\\n8.png")); // NOI18N
        retweetlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retweetlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retweetlbMouseExited(evt);
            }
        });
        add(retweetlb);
        retweetlb.setBounds(110, 570, 100, 50);

        retweetcount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        retweetcount.setText("2");
        add(retweetcount);
        retweetcount.setBounds(220, 580, 40, 40);

        medialb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        add(medialb);
        medialb.setBounds(10, 150, 570, 400);

        replycount.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\A\\n1.png")); // NOI18N
        replycount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                replycountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                replycountMouseExited(evt);
            }
        });
        add(replycount);
        replycount.setBounds(10, 570, 60, 50);

        namelb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namelb.setText("jLabel1");
        add(namelb);
        namelb.setBounds(110, 10, 120, 25);

        snlb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        snlb.setText("jLabel3");
        add(snlb);
        snlb.setBounds(230, 10, 130, 25);

        timelb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        timelb.setText("jLabel4");
        add(timelb);
        timelb.setBounds(360, 10, 160, 25);

        jScrollPane1.setBorder(null);

        searchtweet.setEditable(false);
        searchtweet.setColumns(20);
        searchtweet.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        searchtweet.setLineWrap(true);
        searchtweet.setRows(5);
        searchtweet.setAutoscrolls(false);
        searchtweet.setBorder(null);
        jScrollPane1.setViewportView(searchtweet);

        add(jScrollPane1);
        jScrollPane1.setBounds(110, 40, 480, 100);

        likelb.setText("jLabel1");
        add(likelb);
        likelb.setBounds(280, 570, 60, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void replycountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replycountMouseEntered
 try {
            BufferedImage read1 = ImageIO.read(new File("src\\folder\\n2.png"));
                replycount.setIcon(new ImageIcon(read1));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        
    }//GEN-LAST:event_replycountMouseEntered
    }
    private void replycountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replycountMouseExited
     try {
            BufferedImage read2 = ImageIO.read(new File("src\\folder\\n1.png"));
                replycount.setIcon(new ImageIcon(read2));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_replycountMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
 
    }//GEN-LAST:event_formMouseEntered

    private void retweetlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retweetlbMouseExited
     retweetcount.setForeground(Color.black);
        try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n8.png"));
                retweetlb.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retweetlbMouseExited

    private void retweetlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retweetlbMouseEntered
   retweetcount.setForeground(new Color(25,207,134));
        try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n7.png"));
                retweetlb.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_retweetlbMouseEntered
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel favoritecount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel likelb;
    public javax.swing.JLabel medialb;
    public javax.swing.JLabel namelb;
    public javax.swing.JLabel replycount;
    public javax.swing.JLabel retweetcount;
    public javax.swing.JLabel retweetlb;
    public javax.swing.JLabel searchphotolb;
    public javax.swing.JTextArea searchtweet;
    public javax.swing.JLabel snlb;
    public javax.swing.JLabel timelb;
    // End of variables declaration//GEN-END:variables
}
