
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class singlesearchtweet1 extends javax.swing.JPanel {

    /**
     * Creates new form singlesearchtweet1
     */
    public singlesearchtweet1() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchphotolb = new javax.swing.JLabel();
        favoritecount = new javax.swing.JLabel();
        retweetcount = new javax.swing.JLabel();
        likelb = new javax.swing.JLabel();
        retweetlb = new javax.swing.JLabel();
        namelb = new javax.swing.JLabel();
        timelb = new javax.swing.JLabel();
        replycount = new javax.swing.JLabel();
        snlb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchtweet = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(null);

        searchphotolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(searchphotolb);
        searchphotolb.setBounds(10, 10, 90, 90);

        favoritecount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        favoritecount.setText("2");
        add(favoritecount);
        favoritecount.setBounds(360, 140, 40, 40);

        retweetcount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        retweetcount.setText("2");
        add(retweetcount);
        retweetcount.setBounds(220, 140, 40, 40);
        add(likelb);
        likelb.setBounds(280, 130, 60, 50);

        retweetlb.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\A\\n8.png")); // NOI18N
        retweetlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retweetlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retweetlbMouseExited(evt);
            }
        });
        add(retweetlb);
        retweetlb.setBounds(110, 130, 100, 50);

        namelb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namelb.setText("qwertyuioplkjhg");
        add(namelb);
        namelb.setBounds(110, 10, 120, 25);

        timelb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        timelb.setText("fvdevdf");
        add(timelb);
        timelb.setBounds(360, 10, 160, 25);

        replycount.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARAM\\Documents\\A\\n1.png")); // NOI18N
        replycount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                replycountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                replycountMouseExited(evt);
            }
        });
        add(replycount);
        replycount.setBounds(10, 130, 60, 50);

        snlb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        snlb.setText("rfgrewfgrewf");
        add(snlb);
        snlb.setBounds(230, 10, 130, 25);

        jScrollPane2.setBorder(null);

        searchtweet.setEditable(false);
        searchtweet.setColumns(20);
        searchtweet.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        searchtweet.setLineWrap(true);
        searchtweet.setRows(5);
        searchtweet.setText("dfvdfv\n");
        searchtweet.setAutoscrolls(false);
        jScrollPane2.setViewportView(searchtweet);

        add(jScrollPane2);
        jScrollPane2.setBounds(110, 40, 480, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void retweetlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retweetlbMouseEntered
    retweetcount.setForeground(new Color(25,207,134));
        try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n7.png"));
                retweetlb.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_retweetlbMouseEntered

    private void retweetlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retweetlbMouseExited
   retweetcount.setForeground(Color.black);
        try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n8.png"));
                retweetlb.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retweetlbMouseExited

    private void replycountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replycountMouseEntered
    try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n2.png"));
                replycount.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_replycountMouseEntered

    private void replycountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replycountMouseExited
      try {
            BufferedImage read = ImageIO.read(new File("src\\folder\\n1.png"));
                replycount.setIcon(new ImageIcon(read));
        } catch (IOException ex) {
            Logger.getLogger(singlesearchtweet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_replycountMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel favoritecount;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel likelb;
    public javax.swing.JLabel namelb;
    public javax.swing.JLabel replycount;
    public javax.swing.JLabel retweetcount;
    public javax.swing.JLabel retweetlb;
    public javax.swing.JLabel searchphotolb;
    public javax.swing.JTextArea searchtweet;
    public javax.swing.JLabel snlb;
    public javax.swing.JLabel timelb;
    // End of variables declaration//GEN-END:variables
}
