
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class singletweetpanel extends javax.swing.JPanel {

    /**
     * Creates new form singletweetpanel
     */
    public singletweetpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tweetpanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texttweetarea = new javax.swing.JTextArea();
        textphotolb = new javax.swing.JLabel();
        textcount = new javax.swing.JLabel();
        tweetbt = new javax.swing.JButton();
        photopanel = new javax.swing.JPanel();
        photolb = new javax.swing.JLabel();
        photobrowse = new javax.swing.JTextField();
        browsebt = new javax.swing.JButton();
        photobt = new javax.swing.JButton();
        photocount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        photoarea = new javax.swing.JTextArea();
        locationpanel = new javax.swing.JPanel();
        locationphotolb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationarea = new javax.swing.JTextArea();
        locationcount = new javax.swing.JLabel();
        lcbrowse = new javax.swing.JButton();
        locationbt = new javax.swing.JButton();
        combobx = new javax.swing.JComboBox<>();
        locbrowse = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tweetpanel.setBackground(new java.awt.Color(255, 255, 255));
        tweetpanel.setLayout(null);

        texttweetarea.setEditable(false);
        texttweetarea.setColumns(20);
        texttweetarea.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        texttweetarea.setLineWrap(true);
        texttweetarea.setRows(5);
        texttweetarea.setText("what's happening?");
        texttweetarea.setAutoscrolls(false);
        texttweetarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 161, 255), 2));
        texttweetarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttweetareaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(texttweetarea);

        tweetpanel.add(jScrollPane3);
        jScrollPane3.setBounds(270, 80, 520, 160);
        tweetpanel.add(textphotolb);
        textphotolb.setBounds(130, 120, 120, 120);

        textcount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textcount.setForeground(new java.awt.Color(29, 161, 242));
        textcount.setText("280");
        tweetpanel.add(textcount);
        textcount.setBounds(850, 200, 60, 50);

        tweetbt.setBackground(new java.awt.Color(29, 161, 242));
        tweetbt.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        tweetbt.setForeground(new java.awt.Color(255, 255, 255));
        tweetbt.setText("Tweet");
        tweetbt.setEnabled(false);
        tweetbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tweetbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tweetbtMouseExited(evt);
            }
        });
        tweetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetbtActionPerformed(evt);
            }
        });
        tweetpanel.add(tweetbt);
        tweetbt.setBounds(460, 310, 180, 50);

        jTabbedPane1.addTab("text tweet", tweetpanel);

        photopanel.setBackground(new java.awt.Color(255, 255, 255));
        photopanel.setLayout(null);

        photolb.setText("photo here");
        photopanel.add(photolb);
        photolb.setBounds(110, 110, 120, 120);

        photobrowse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 161, 242), 1, true));
        photobrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobrowseActionPerformed(evt);
            }
        });
        photopanel.add(photobrowse);
        photobrowse.setBounds(140, 310, 200, 50);

        browsebt.setBackground(new java.awt.Color(29, 161, 242));
        browsebt.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        browsebt.setForeground(new java.awt.Color(255, 255, 255));
        browsebt.setText("Browse");
        browsebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browsebtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                browsebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                browsebtMouseExited(evt);
            }
        });
        browsebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtActionPerformed(evt);
            }
        });
        photopanel.add(browsebt);
        browsebt.setBounds(770, 310, 150, 50);

        photobt.setBackground(new java.awt.Color(29, 161, 242));
        photobt.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        photobt.setForeground(new java.awt.Color(255, 255, 255));
        photobt.setText("Tweet");
        photobt.setEnabled(false);
        photobt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                photobtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                photobtMouseExited(evt);
            }
        });
        photobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobtActionPerformed(evt);
            }
        });
        photopanel.add(photobt);
        photobt.setBounds(460, 310, 180, 50);

        photocount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        photocount.setForeground(new java.awt.Color(29, 161, 242));
        photocount.setText("280");
        photopanel.add(photocount);
        photocount.setBounds(840, 190, 60, 50);

        photoarea.setEditable(false);
        photoarea.setColumns(20);
        photoarea.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        photoarea.setLineWrap(true);
        photoarea.setRows(5);
        photoarea.setText("what's happening?");
        photoarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 161, 242), 2, true));
        photoarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoareaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(photoarea);

        photopanel.add(jScrollPane1);
        jScrollPane1.setBounds(270, 80, 520, 160);

        jTabbedPane1.addTab("photo tweet", photopanel);

        locationpanel.setBackground(new java.awt.Color(255, 255, 255));
        locationpanel.setLayout(null);
        locationpanel.add(locationphotolb);
        locationphotolb.setBounds(110, 100, 120, 120);

        locationarea.setColumns(20);
        locationarea.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        locationarea.setLineWrap(true);
        locationarea.setRows(5);
        locationarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 161, 242), 2, true));
        locationarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationareaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(locationarea);

        locationpanel.add(jScrollPane2);
        jScrollPane2.setBounds(270, 80, 520, 160);

        locationcount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        locationcount.setForeground(new java.awt.Color(29, 161, 242));
        locationcount.setText("280");
        locationpanel.add(locationcount);
        locationcount.setBounds(820, 190, 60, 50);

        lcbrowse.setBackground(new java.awt.Color(29, 161, 242));
        lcbrowse.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        lcbrowse.setForeground(new java.awt.Color(255, 255, 255));
        lcbrowse.setText("browse");
        lcbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcbrowseActionPerformed(evt);
            }
        });
        locationpanel.add(lcbrowse);
        lcbrowse.setBounds(550, 330, 170, 50);

        locationbt.setBackground(new java.awt.Color(29, 161, 242));
        locationbt.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        locationbt.setForeground(new java.awt.Color(255, 255, 255));
        locationbt.setText("Tweet");
        locationbt.setEnabled(false);
        locationbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                locationbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                locationbtMouseExited(evt);
            }
        });
        locationbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationbtActionPerformed(evt);
            }
        });
        locationpanel.add(locationbt);
        locationbt.setBounds(310, 330, 180, 50);

        combobx.setBackground(new java.awt.Color(29, 161, 242));
        combobx.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        combobx.setForeground(new java.awt.Color(255, 255, 255));
        combobx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobxActionPerformed(evt);
            }
        });
        locationpanel.add(combobx);
        combobx.setBounds(80, 330, 170, 50);

        locbrowse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 161, 242)));
        locationpanel.add(locbrowse);
        locbrowse.setBounds(810, 330, 180, 50);

        jTabbedPane1.addTab("location tweet", locationpanel);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 0, 1056, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void tweetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweetbtActionPerformed

    private void photobrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photobrowseActionPerformed

    private void locationbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationbtActionPerformed

    private void lcbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcbrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcbrowseActionPerformed

    private void photobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photobtActionPerformed

    private void browsebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browsebtActionPerformed

    private void tweetbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tweetbtMouseEntered
   tweetbt.setBackground(new Color(30,21,90));
    }//GEN-LAST:event_tweetbtMouseEntered

    private void tweetbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tweetbtMouseExited
   tweetbt.setBackground(new Color(29,161,242));     
    }//GEN-LAST:event_tweetbtMouseExited

    private void photobtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photobtMouseEntered
     photobt.setBackground(new Color(30,21,90));
    }//GEN-LAST:event_photobtMouseEntered

    private void photobtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photobtMouseExited
   photobt.setBackground(new Color(29,161,242));    
    }//GEN-LAST:event_photobtMouseExited

    private void browsebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebtMouseEntered
     browsebt.setBackground(new Color(30,21,90));     
    }//GEN-LAST:event_browsebtMouseEntered

    private void browsebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebtMouseExited
     browsebt.setBackground(new Color(29,161,242));    
    }//GEN-LAST:event_browsebtMouseExited

    private void locationbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationbtMouseEntered
         locationbt.setBackground(new Color(30,21,90));    
       // TODO add your handling code here
    }//GEN-LAST:event_locationbtMouseEntered

    private void locationbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationbtMouseExited
 locationbt.setBackground(new Color(29,161,242));       // TODO add your handling code here:
    }//GEN-LAST:event_locationbtMouseExited

    private void locationareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationareaMouseClicked
locationbt.setEnabled(true);
       locationarea.setEditable(true);
        locationarea.setText("");
    }//GEN-LAST:event_locationareaMouseClicked

    private void texttweetareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttweetareaMouseClicked
texttweetarea.setEditable(true);
tweetbt.setEnabled(true);
        texttweetarea.setText("");
    }//GEN-LAST:event_texttweetareaMouseClicked

    private void photoareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoareaMouseClicked
photobt.setEnabled(true);
        photoarea.setEditable(true);
        photoarea.setText("");
    }//GEN-LAST:event_photoareaMouseClicked

    private void browsebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebtMouseClicked
     photobt.setEnabled(true);
   ///     photoarea.setEditable(true);
        
    }//GEN-LAST:event_browsebtMouseClicked

    private void combobxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton browsebt;
    public javax.swing.JComboBox<String> combobx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton lcbrowse;
    public javax.swing.JTextArea locationarea;
    public javax.swing.JButton locationbt;
    public javax.swing.JLabel locationcount;
    public javax.swing.JPanel locationpanel;
    public javax.swing.JLabel locationphotolb;
    public javax.swing.JTextField locbrowse;
    public javax.swing.JTextArea photoarea;
    public javax.swing.JTextField photobrowse;
    public javax.swing.JButton photobt;
    public javax.swing.JLabel photocount;
    public javax.swing.JLabel photolb;
    public javax.swing.JPanel photopanel;
    public javax.swing.JLabel textcount;
    public javax.swing.JLabel textphotolb;
    public javax.swing.JTextArea texttweetarea;
    public javax.swing.JButton tweetbt;
    public javax.swing.JPanel tweetpanel;
    // End of variables declaration//GEN-END:variables
}
