
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class singledmpanel extends javax.swing.JPanel {

    /**
     * Creates new form singledmpanel
     */
    public singledmpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dmlb = new javax.swing.JLabel();
        dmname = new javax.swing.JLabel();
        dmscr = new javax.swing.JLabel();
        msgdt = new javax.swing.JLabel();
        singlemsg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(null);

        dmlb.setText("jLabel1");
        dmlb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(dmlb);
        dmlb.setBounds(20, 13, 90, 90);

        dmname.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        dmname.setText("qwertyuoplkjhg");
        add(dmname);
        dmname.setBounds(130, 20, 170, 30);

        dmscr.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dmscr.setText("qwertyuioplkjhg");
        add(dmscr);
        dmscr.setBounds(290, 20, 220, 30);

        msgdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        msgdt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(msgdt);
        msgdt.setBounds(780, 20, 190, 30);

        singlemsg.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        singlemsg.setText("jLabel1");
        add(singlemsg);
        singlemsg.setBounds(130, 60, 900, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(204,240,255));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
       setBackground(Color.white);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel dmlb;
    public javax.swing.JLabel dmname;
    public javax.swing.JLabel dmscr;
    public javax.swing.JLabel msgdt;
    public javax.swing.JLabel singlemsg;
    // End of variables declaration//GEN-END:variables
}
