/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class statusnullnotif extends javax.swing.JPanel {

    /**
     * Creates new form statusnullnotif
     */
    public statusnullnotif() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notiflb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        notiflb.setFont(new java.awt.Font("Verdana", 1, 70)); // NOI18N
        notiflb.setForeground(new java.awt.Color(29, 161, 242));
        notiflb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/twitmain2.png"))); // NOI18N
        notiflb.setText("  No Tweets Yet ?!!");
        notiflb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 161, 242), 3));
        add(notiflb);
        notiflb.setBounds(0, 1, 1000, 200);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel notiflb;
    // End of variables declaration//GEN-END:variables
}
