
import java.awt.Color;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARAM
 */
public class tweetframe extends javax.swing.JFrame {

    /**
     * Creates new form tweetframe
     */
    public tweetframe() {
        initComponents();
        getContentPane().setBackground(new Color(204,240,255));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textphotolb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texttweetarea = new javax.swing.JTextArea();
        tweetbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        browsebt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textcount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 161, 242)));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/close4.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(730, 0, 90, 90);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Compose a new Tweet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 10, 340, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 90);

        textphotolb.setText("jLabel3");
        getContentPane().add(textphotolb);
        textphotolb.setBounds(10, 100, 70, 70);

        texttweetarea.setColumns(20);
        texttweetarea.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        texttweetarea.setRows(5);
        texttweetarea.setText("\n What's Happening?");
        texttweetarea.setBorder(null);
        texttweetarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttweetareaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(texttweetarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(96, 100, 730, 150);

        tweetbt.setBackground(new java.awt.Color(29, 161, 242));
        tweetbt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tweetbt.setForeground(new java.awt.Color(255, 255, 255));
        tweetbt.setText("TWEET");
        tweetbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tweetbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tweetbtMouseExited(evt);
            }
        });
        tweetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetbtActionPerformed(evt);
            }
        });
        getContentPane().add(tweetbt);
        tweetbt.setBounds(650, 270, 150, 60);

        jPanel2.setBackground(new java.awt.Color(204, 240, 255));
        jPanel2.setLayout(null);

        browsebt.setBackground(new java.awt.Color(51, 255, 255));
        browsebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/gall.png"))); // NOI18N
        browsebt.setText("jLabel4");
        browsebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                browsebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                browsebtMouseExited(evt);
            }
        });
        jPanel2.add(browsebt);
        browsebt.setBounds(0, 0, 80, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(130, 260, 80, 80);

        jPanel3.setBackground(new java.awt.Color(204, 240, 255));
        jPanel3.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/locc.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 80, 80);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(320, 260, 80, 80);

        textcount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textcount.setText("23");
        getContentPane().add(textcount);
        textcount.setBounds(20, 210, 70, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tweetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweetbtActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void browsebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebtMouseEntered
///jPanel2.setBackground(new Color(135,206,235));
        javax.swing.border.Border br1 = BorderFactory.createLineBorder(new Color(29,161,242), 1);
        jPanel2.setBorder(br1);
    }//GEN-LAST:event_browsebtMouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
      ///  jPanel3.setBackground(new Color(135,206,235));
            javax.swing.border.Border br1 = BorderFactory.createLineBorder(new Color(29,161,242), 1);
        jPanel3.setBorder(br1);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void browsebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebtMouseExited
        jPanel2.setBorder(null);
        
    }//GEN-LAST:event_browsebtMouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
             jPanel3.setBorder(null);
        
    }//GEN-LAST:event_jLabel5MouseExited

    private void tweetbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tweetbtMouseEntered
  tweetbt.setBackground(new Color(30,21,90));
    }//GEN-LAST:event_tweetbtMouseEntered

    private void tweetbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tweetbtMouseExited
    tweetbt.setBackground(new Color(29,161,242));
    }//GEN-LAST:event_tweetbtMouseExited

    private void texttweetareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttweetareaMouseClicked
       texttweetarea.setText("");
          javax.swing.border.Border br1 = BorderFactory.createLineBorder(new Color(29,161,242), 1);
       texttweetarea.setBorder(br1);
    }//GEN-LAST:event_texttweetareaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tweetframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tweetframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tweetframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tweetframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tweetframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel browsebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel textcount;
    public javax.swing.JLabel textphotolb;
    public javax.swing.JTextArea texttweetarea;
    public javax.swing.JButton tweetbt;
    // End of variables declaration//GEN-END:variables
}
